debug:
  death: false
  remove: false
  spawn:
    natural: false
    reinforcement: false

difficulty:
  # Scaling factor applied to the vanilla creeper blast radius.
  blastscale: 0.5

  # Probability, [0.0, 1.0], that a non-spawner, overworld hostile mob is
  # replaced with a blaze.
  blaze:
    chance: 0.1

reinforcements:
  # Minimum and maximum number of reinforcements spawned on creeper detonation.
  min: 1
  max: 3

  # Distance (blocks) of spawned reinforcement from detonation.
  range: 2.0

  # Magnitude of initial velocity given to spawned reinforcement.
  velocity:
    min: 0.0
    max: 2.0

  # Chance that an egg launched by a disguised skeleton will spawn a
  # reinforcement.
  egg:
    chance: 0.125

# Chance values express the base probability, [0.0, 1.0], of dropping an item.
# Probability is increased by 1% per looting level.
drops:
  feather:
    chance: 0.4
    name: "&eTurkey Feather"
    lore: "&6Thanksgiving 2016"

  egg:
    chance: 0.1
    name: "&eTurkey Egg"
    lore: "&6Thanksgiving 2016"

  corpse:
    chance: 0.1
    name:
      raw: "&eA Dead Angry Bird"
      cooked: "&eCooked Turkey"

    lore: "&6Thanksgiving 2016|&oDon't let the turkeys get you down!"

  wishbone:
    chance: 0.025
    name: "&eWishbone"
    lore: "&6Thanksgiving 2016|&oMake a wish!"

  stuffing:
    chance: 0.1
    name: "&eStuffing"
    lore: "&6Thanksgiving 2016|&oYou knocked the stuffing out of it!"

  cranberry_sauce:
    chance: 0.05
    name: "&eCranberry Sauce"
    lore: "&6Thanksgiving 2016|&oTime to hit the sauce!"

  pumpkin_pie:
    chance: 0.1
    name: "&ePumpkin Pie"
    lore: "&6Thanksgiving 2016|&oDessert!"

messages:
  turkey:
  - "a foul fowl"
  - "a very angry bird"
  - "irate poultry"
  - "a furious avian assailant"
  - "an angry avian assailant"
  - "an enraged maple roast turkey"
  - "an utterly livid rosemary roasted turkey"
  - "an indignant turkey pot pie"
  - "a surly family meal"
  - "some turkey"
  - "some punk-ass jive turkey"
  - "the other, other, other white meat"
  - "a well-roasted turkey"
  - "a thoroughly baked turkey"
  - "a spicy chipotle turkey burger"
  - "the entire nation of Turkey"
