name: ${project.name}
version: ${project.version}
author: totemo
authors: [totemo]
description: ${project.description}
website: ${project.url}
depend: [LibsDisguises]
main: io.totemo.iratepoultry.IratePoultry

permissions:
  iratepoultry.admin:
    description: Permission to administer the plugin.
    default: op

commands:
  iratepoultry:
    description: Main plugin command.
    permission: iratepoultry.admin
    usage: |
      /<command> reload: Reload the configuration.
